import type { PipelineStep } from '../index'
import type { BuildContext } from '../types'

export class RouteGenerateStep implements PipelineStep<BuildContext> {
  name = 'RouteGenerate'

  async execute(ctx: BuildContext): Promise<void> {
    // ConfigResolveStep already materialized routes and set ctx.ssgRoutes.
    // Both fields are guaranteed to be populated before this step runs.
    if (!ctx.routes) {
      throw new Error(
        'Routes not generated by ConfigResolveStep. Verify pipeline order.',
      )
    }
  }
}
