import type { PipelineStep } from '../index'
import type { BuildContext } from '../types'

/**
 * Fires the plugin `build:routes` hook.
 *
 * This is the only point in the build where a plugin can still influence what
 * gets rendered: routes exist, and the SSG render has not started. `@bdocs/plugin-seo`
 * uses it to resolve `canonical` and `og:url` against `siteUrl`, which the client
 * `Head` reads during render.
 *
 * Plugins mutate the route objects in place. Replacing the array has no effect —
 * `ctx.routes` and `ctx.ssgRoutes` are read from here on.
 */
export class RoutesEnrichStep implements PipelineStep<BuildContext> {
  name = 'RoutesEnrich'

  async execute(ctx: BuildContext): Promise<void> {
    const plugins = ctx.config?.plugins
    if (!plugins || plugins.length === 0) return
    if (!ctx.routes) {
      throw new Error(
        'Routes not generated by RouteGenerateStep. Verify pipeline order.',
      )
    }
    if (!ctx.config) return

    const docsDir = ctx.docsDir || `${ctx.root}/docs`
    const { PluginLifecycleManager } = await import(
      '../../plugins/plugin-lifecycle'
    )
    const manager = new PluginLifecycleManager(
      plugins,
      ctx.config,
      docsDir,
      ctx.root,
      ctx.routes,
      ctx.outDir ?? '',
    )
    await manager.runHook('build:routes', { routes: ctx.routes })
  }
}
