import type { PipelineStep } from '../index'
import type { BuildContext } from '../types'

export class TypeGenerateStep implements PipelineStep<BuildContext> {
  name = 'TypeGenerate'

  async execute(ctx: BuildContext): Promise<void> {
    // ConfigResolveStep already generated types + link-tree.
    // ctx.typesGenerated is guaranteed to be true at this point.
    if (ctx.typesGenerated) return
    throw new Error(
      'Types not generated by ConfigResolveStep. Verify pipeline order.',
    )
  }
}
