import { useState } from 'react'
import {
  CircleDot,
  Clock,
  Hammer,
  CheckCircle2,
  LoaderCircle,
  Package,
  ArrowUpRight,
} from 'lucide-react'
import { cn } from 'boltdocs/client'
import { Section } from '@/theme/section'

type RoadmapItem = {
  title: string
  description: string
  status: 'shipped' | 'in-progress' | 'planning'
}

const ROADMAP: RoadmapItem[] = [
  // Shipped in 3.4.0
  {
    title: 'Redirects',
    description:
      'Declarative redirects via config with 301/302/307/308, loop detection, chain collapsing, locale mirroring, and static HTML output.',
    status: 'shipped',
  },
  {
    title: 'Instant Navigation',
    description:
      'View Transitions with directional types, live prefers-reduced-motion support, and full-site dev prewarming.',
    status: 'shipped',
  },
  {
    title: 'Incremental SSG',
    description:
      'Content-addressed page cache. A single page edit recompiles and re-renders one route instead of the whole site.',
    status: 'shipped',
  },
  {
    title: 'Shared contracts',
    description:
      '@bdocs/contracts publishes the framework-neutral route, plugin, lifecycle, and configuration contracts used by 4.0.',
    status: 'shipped',
  },
  // In Progress
  {
    title: 'Boltdocs migrate MVP — VitePress first',
    description:
      'A first-party migration tool to move existing VitePress sites to Boltdocs with minimal friction.',
    status: 'in-progress',
  },
  {
    title: 'Virtual routes',
    description:
      'Routes generated by plugins, unlocking fully dynamic documentation trees.',
    status: 'in-progress',
  },
  // Planning
  {
    title: 'Search & primitive improvements',
    description: 'Consolidate the public API and harden the search primitives.',
    status: 'planning',
  },
  {
    title: 'Plugin: tabs-sync',
    description: 'Tabs that stay in sync across pages on the same visit.',
    status: 'planning',
  },
  {
    title: 'Plugin: reading-time',
    description: 'Reading time derived automatically from content.',
    status: 'planning',
  },
  {
    title: 'Plugin: last-updated',
    description: 'Last-updated dates sourced from git history.',
    status: 'planning',
  },
  {
    title: 'Plugin: contributors',
    description: 'Author and contributor lists derived from git.',
    status: 'planning',
  },
  {
    title: 'Plugin: video',
    description: 'Embed YouTube, Loom, and Vimeo natively.',
    status: 'planning',
  },
  {
    title: 'Plugin: code-diff',
    description: 'Diffs tailored for migration guides.',
    status: 'planning',
  },
  {
    title: 'Plugin: shiki-twoslash',
    description: 'Inline TypeScript type annotations in code blocks.',
    status: 'planning',
  },
  {
    title: 'Plugin: cookie-consent',
    description: 'GDPR-ready cookie consent banners.',
    status: 'planning',
  },
  {
    title: 'Plugin: plausible',
    description: 'Privacy-first, lightweight analytics.',
    status: 'planning',
  },
  {
    title: 'Plugin: Fathom',
    description: 'Privacy-first website analytics integration.',
    status: 'planning',
  },
  {
    title: 'Plugin: pagefind',
    description: 'Local, backend-free search for your docs.',
    status: 'planning',
  },
  {
    title: 'Plugin: utterances',
    description: 'GitHub-based comments for docs pages.',
    status: 'planning',
  },
  {
    title: 'Plugin: hotjar',
    description: 'Heatmaps and session replay.',
    status: 'planning',
  },
  {
    title: 'Plugin: meilisearch',
    description: 'Self-hosted full-text search.',
    status: 'planning',
  },
  {
    title: 'Plugin: directive',
    description: 'Custom directives within MDX content.',
    status: 'planning',
  },
  {
    title: 'Plugin: storybook',
    description: 'Embed Storybook stories in your docs.',
    status: 'planning',
  },
  {
    title: 'create-plugin scaffolder',
    description: 'Official CLI scaffolder for new Boltdocs plugins.',
    status: 'planning',
  },
  {
    title: 'Full migration tool',
    description:
      'A comprehensive tool to migrate any existing documentation setup to Boltdocs.',
    status: 'planning',
  },
]

const MIGRATION_ROUTE = [
  {
    step: 'Shared contracts',
    package: '@bdocs/contracts',
    status: 'Done',
    description:
      'Route, plugin, lifecycle, highlighting, and configuration contracts extracted from the core with backward-compatible re-exports.',
  },
  {
    step: 'SEO extraction',
    package: '@bdocs/plugin-seo',
    status: 'Next',
    description:
      'Move sitemap, robots, metadata, Open Graph, and structured data behind the plugin API. The core keeps only the orchestration.',
  },
  {
    step: 'UI extraction',
    package: '@bdocs/ui',
    status: 'Planned',
    description:
      'Move the ui-base components into their own package while keeping the existing boltdocs exports working.',
  },
  {
    step: 'Primitives extraction',
    package: '@bdocs/primitives',
    status: 'Planned',
    description:
      'Move the style-neutral primitives out of the core. Primitives keep owning structure and data-* state, never colors.',
  },
  {
    step: 'Runtime boundary',
    package: '@bdocs/runtime',
    status: 'Planned',
    description:
      'Separate the browser runtime from the Node build engine so neither pulls in the other dependencies.',
  },
  {
    step: 'Incremental MDX and SSG',
    package: 'core, Sätteri, SSG',
    status: 'In progress',
    description:
      'Per-module identities and dependency edges so a single edit invalidates only the modules and routes it actually affects.',
  },
  {
    step: 'Migration tooling',
    package: 'repository-wide',
    status: 'Planned',
    description:
      'Codemods, compatibility adapters, diagnostics, and the upgrade guide for package imports and removed private APIs.',
  },
]

const STATUS_META = {
  shipped: {
    label: 'Shipped',
    icon: CheckCircle2,
    accent: 'text-success-500',
    badgeBg: 'bg-success-500/10 text-success-500',
  },
  'in-progress': {
    label: 'In Progress',
    icon: LoaderCircle,
    accent: 'text-accent-400',
    badgeBg: 'bg-accent-500/10 text-accent-400',
  },
  planning: {
    label: 'Planning',
    icon: CircleDot,
    accent: 'text-muted',
    badgeBg: 'bg-subtle text-muted',
  },
} as const

type MigrationStep = (typeof MIGRATION_ROUTE)[number]

const MIGRATION_STATUS_STYLES: Record<string, string> = {
  Done: 'bg-success-500 text-white',
  Next: 'bg-accent-500 text-white',
  'In progress': 'bg-accent-500/15 text-accent-400',
  Planned: 'bg-subtle text-muted',
}

function StatusPill({ status }: { status: RoadmapItem['status'] }) {
  if (status === 'shipped') {
    return (
      <span className="inline-flex items-center gap-1 rounded-full bg-success-500/10 px-2 py-0.5 text-[11px] font-medium text-success-500">
        <CheckCircle2 className="size-3" /> Shipped
      </span>
    )
  }
  if (status === 'in-progress') {
    return (
      <span className="inline-flex items-center gap-1 rounded-full bg-accent-500/10 px-2 py-0.5 text-[11px] font-medium text-accent-400">
        <LoaderCircle className="size-3 animate-spin" /> Active
      </span>
    )
  }
  return (
    <span className="inline-flex items-center gap-1 rounded-full bg-subtle px-2 py-0.5 text-[11px] font-medium text-muted">
      <Clock className="size-3" /> Planned
    </span>
  )
}

function RoadmapItemCard({ item }: { item: RoadmapItem }) {
  const Icon = STATUS_META[item.status].icon

  return (
    <article className="group flex flex-col gap-3 rounded-2xl bg-surface p-4 transition-colors hover:bg-surface-2 sm:p-5">
      <div className="flex items-start justify-between gap-3">
        <div
          className={`flex size-8 shrink-0 items-center justify-center rounded-lg ${STATUS_META[item.status].badgeBg}`}
        >
          <Icon
            className={`size-4 ${item.status === 'in-progress' ? 'animate-spin' : ''}`}
          />
        </div>
        <StatusPill status={item.status} />
      </div>
      <div className="min-w-0">
        <h3 className="text-sm font-semibold leading-snug text-body">
          {item.title}
        </h3>
        <p className="mt-1 text-[13px] leading-relaxed text-paragraph">
          {item.description}
        </p>
      </div>
    </article>
  )
}

/**
 * Compact variant used for the long "Planning" list.
 *
 * The planning backlog is mostly short `Plugin: name` entries, so rendering
 * each one as a full card turns the page into an endless scroll. These render
 * as dense rows that keep the same information at roughly a third of the
 * height.
 */
function RoadmapItemRow({ item }: { item: RoadmapItem }) {
  return (
    <li className="flex items-start gap-2.5 rounded-xl bg-surface px-3.5 py-2.5">
      <CircleDot className="mt-0.5 size-3.5 shrink-0 text-dim" />
      <div className="min-w-0">
        <h3 className="text-[13px] font-medium leading-snug text-body">
          {item.title}
        </h3>
        <p className="mt-0.5 text-xs leading-relaxed text-muted">
          {item.description}
        </p>
      </div>
    </li>
  )
}

function SectionHeading({
  icon: Icon,
  label,
  tone,
  count,
}: {
  icon: typeof Hammer
  label: string
  tone: string
  count: number
}) {
  return (
    <div className="mb-4 flex items-center gap-3">
      <div
        className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-sm font-semibold ${tone}`}
      >
        <Icon className="size-4" />
        {label}
        <span className="text-xs font-normal opacity-70">{count}</span>
      </div>
      <div className="h-px flex-1 bg-subtle" />
    </div>
  )
}

function MigrationStepper({ steps }: { steps: MigrationStep[] }) {
  return (
    <ol className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
      {steps.map((step, index) => (
        <li
          key={step.step}
          className="relative flex gap-3 rounded-2xl bg-surface p-4"
        >
          <div className="flex flex-col items-center gap-2">
            <span
              className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${MIGRATION_STATUS_STYLES[step.status] ?? MIGRATION_STATUS_STYLES.Planned}`}
            >
              {index + 1}
            </span>
            {index < steps.length - 1 && (
              <span
                className="hidden w-px flex-1 bg-subtle sm:block"
                aria-hidden="true"
              />
            )}
          </div>
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
              <h3 className="text-sm font-semibold leading-snug text-body">
                {step.step}
              </h3>
              <code className="rounded bg-subtle px-1.5 py-0.5 text-[11px] text-muted">
                {step.package}
              </code>
            </div>
            <p className="mt-1.5 text-[13px] leading-relaxed text-paragraph">
              {step.description}
            </p>
            <span className="mt-2 inline-block text-[11px] font-medium text-muted">
              {step.status}
            </span>
          </div>
        </li>
      ))}
    </ol>
  )
}

export default function RoadmapPage() {
  const [tab, setTab] = useState<
    'all' | 'shipped' | 'in-progress' | 'planning'
  >('all')

  const shipped = ROADMAP.filter((i) => i.status === 'shipped')
  const inProgress = ROADMAP.filter((i) => i.status === 'in-progress')
  const planning = ROADMAP.filter((i) => i.status === 'planning')
  const visible =
    tab === 'all'
      ? ROADMAP
      : tab === 'shipped'
        ? shipped
        : tab === 'in-progress'
          ? inProgress
          : planning

  const tabs = [
    { key: 'all' as const, label: `All (${ROADMAP.length})` },
    { key: 'shipped' as const, label: `Shipped (${shipped.length})` },
    {
      key: 'in-progress' as const,
      label: `In Progress (${inProgress.length})`,
    },
    { key: 'planning' as const, label: `Planned (${planning.length})` },
  ]

  const showSections = tab === 'all'
  const compactList = tab === 'planning' || !showSections

  return (
    <div className="min-h-screen overflow-hidden bg-body font-sans text-body antialiased">
      <Section padding="sm" maxWidth="xl">
        <header className="mx-auto mb-6 max-w-3xl text-center">
          <h1 className="text-3xl font-semibold tracking-tighter text-body md:text-5xl">
            What&apos;s coming next
          </h1>
          <p className="mx-auto mt-3 text-sm text-paragraph md:text-base">
            Boltdocs 3.4 is the stable line: redirects, incremental builds,
            accessible View Transitions, and the shared contract layer. The 4.0
            architecture migration continues in parallel on a dedicated branch.
          </p>
          <div className="mt-5 flex flex-wrap items-center justify-center gap-x-5 gap-y-2 text-xs text-paragraph">
            <span className="inline-flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-success-500" />
              {shipped.length} shipped
            </span>
            <span className="inline-flex items-center gap-1.5">
              <span className="size-2 animate-pulse rounded-full bg-accent-500" />
              {inProgress.length} in progress
            </span>
            <span className="inline-flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-dim/60" />
              {planning.length} planned
            </span>
          </div>
        </header>

        <div className="sticky top-16 z-20 -mx-2 mb-6 flex justify-center px-2 py-2 backdrop-blur-sm">
          <div
            role="tablist"
            aria-label="Roadmap filters"
            className="inline-flex max-w-full items-center gap-1 overflow-x-auto rounded-full bg-surface p-1"
          >
            {tabs.map((t) => (
              <button
                key={t.key}
                role="tab"
                aria-selected={tab === t.key}
                onClick={() => setTab(t.key)}
                className={cn(
                  'cursor-pointer whitespace-nowrap rounded-full px-4 py-1.5 text-xs font-medium transition-all duration-300 md:text-sm',
                  {
                    'bg-primary-500/15 text-primary-30': tab === t.key,
                    'text-muted hover:text-body': tab !== t.key,
                  },
                )}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {showSections ? (
          <div className="flex flex-col gap-8">
            <section aria-labelledby="shipped-heading">
              <div id="shipped-heading">
                <SectionHeading
                  icon={CheckCircle2}
                  label="Shipped in 3.4.0"
                  tone="bg-success-500/10 text-success-500"
                  count={shipped.length}
                />
              </div>
              <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
                {shipped.map((item) => (
                  <RoadmapItemCard key={item.title} item={item} />
                ))}
              </div>
            </section>

            <section aria-labelledby="progress-heading">
              <div id="progress-heading">
                <SectionHeading
                  icon={Hammer}
                  label="In Progress"
                  tone="bg-accent-500/10 text-accent-400"
                  count={inProgress.length}
                />
              </div>
              <div className="grid gap-3 sm:grid-cols-2">
                {inProgress.map((item) => (
                  <RoadmapItemCard key={item.title} item={item} />
                ))}
              </div>
            </section>

            <section aria-labelledby="planned-heading">
              <div id="planned-heading">
                <SectionHeading
                  icon={CircleDot}
                  label="Planned"
                  tone="bg-surface text-muted"
                  count={planning.length}
                />
              </div>
              <ul className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">
                {planning.map((item) => (
                  <RoadmapItemRow key={item.title} item={item} />
                ))}
              </ul>
            </section>
          </div>
        ) : (
          <ul
            className={cn(
              'grid gap-2',
              compactList
                ? 'md:grid-cols-2 xl:grid-cols-3'
                : 'sm:grid-cols-2 xl:grid-cols-4',
            )}
          >
            {visible.map((item) =>
              item.status === 'planning' ? (
                <RoadmapItemRow key={item.title} item={item} />
              ) : (
                <li key={item.title} className="contents">
                  <RoadmapItemCard item={item} />
                </li>
              ),
            )}
          </ul>
        )}

        <section className="mt-10" aria-labelledby="migration-heading">
          <div className="mb-2 flex items-center gap-3">
            <h2
              id="migration-heading"
              className="inline-flex items-center gap-2 rounded-full bg-surface px-3 py-1 text-sm font-semibold text-body"
            >
              <Package className="size-4" />
              Boltdocs 4.0 migration
            </h2>
            <div className="h-px flex-1 bg-subtle" />
          </div>
          <p className="mb-4 max-w-3xl text-[13px] text-paragraph">
            4.0 is an architecture release, not a feature release. The goal is a
            smaller core with explicit package boundaries, optional
            integrations, and builds whose cost is proportional to the change.
            Every slice ships on the <code>4.0</code> branch and is merged back
            into <code>develop</code> only when it is backward compatible.
          </p>

          <MigrationStepper steps={MIGRATION_ROUTE} />

          <a
            href="https://github.com/bolt-docs/boltdocs/blob/4.0/ROADMAP-4.0.md"
            target="_blank"
            rel="noreferrer"
            className="mt-4 inline-flex items-center gap-1.5 text-sm font-medium text-accent-400 transition-colors hover:text-accent-300"
          >
            Read the full 4.0 roadmap
            <ArrowUpRight className="size-4" />
          </a>
        </section>
      </Section>
    </div>
  )
}
