import fs from 'node:fs'
import path from 'node:path'
import type { BoltdocsConfig } from '../shared/types'

/**
 * Generates a declaration file (.boltdocs/types.d.ts) to provide strict typing
 * for locales, versions, and custom components based on the project files.
 */
export function generateProjectTypes(
  config: BoltdocsConfig,
  docsDir: string,
  root: string = process.cwd(),
) {
  const dotBoltdocsDir = path.resolve(root, '.boltdocs')
  if (!fs.existsSync(dotBoltdocsDir)) {
    fs.mkdirSync(dotBoltdocsDir, { recursive: true })
  }

  const locales = config.i18n ? Object.keys(config.i18n.locales) : []
  const versions = config.versions
    ? config.versions.versions.map((v) => v.path)
    : []

  const localeType =
    locales.length > 0 ? locales.map((l) => `'${l}'`).join(' | ') : 'string'
  const versionType =
    versions.length > 0 ? versions.map((v) => `'${v}'`).join(' | ') : 'string'

  // Scan for custom mdx-components within the user's docs directory
  const extensions = ['tsx', 'ts', 'jsx', 'js']
  let mdxComponentsImport = ''
  let mdxComponentsTypeRef = ''

  for (const ext of extensions) {
    const fullPath = path.resolve(root, docsDir, `mdx-components.${ext}`)
    if (fs.existsSync(fullPath)) {
      // Compute relative import path from the generated type file to the user component file
      const baseMdxPath = path.join(root, docsDir, 'mdx-components')
      const relativePath = path.relative(dotBoltdocsDir, baseMdxPath)
      const normalizedPath = relativePath.replace(/\\/g, '/')
      const importPath = normalizedPath.startsWith('.')
        ? normalizedPath
        : `./${normalizedPath}`

      mdxComponentsImport = `import type * as MdxComponentsModule from '${importPath}'\n`
      mdxComponentsTypeRef = `      MdxComponents: typeof MdxComponentsModule`
      break
    }
  }

  const content = `// This file is automatically generated by Boltdocs.
// Do not edit this file manually.

${mdxComponentsImport}declare global {
  namespace Boltdocs {
    interface Types {
      Locale: ${localeType}
      Version: ${versionType}${mdxComponentsTypeRef ? `\n${mdxComponentsTypeRef}` : ''}
    }
  }
}

export {}
`

  fs.writeFileSync(path.resolve(dotBoltdocsDir, 'types.d.ts'), content)
}
