import fs from 'node:fs'
import path from 'node:path'
import type { BoltdocsConfig } from '../shared/types'

/**
 * Generates a declaration file (.boltdocs/generated/types.d.ts) to provide strict typing
 * for locales, versions, route paths, and custom components based on the project files.
 */
export function generateProjectTypes(
  config: BoltdocsConfig,
  docsDir: string,
  root: string = process.cwd(),
  routePaths?: string[],
) {
  const dotBoltdocsDir = path.resolve(root, '.boltdocs', 'generated')
  if (!fs.existsSync(dotBoltdocsDir)) {
    fs.mkdirSync(dotBoltdocsDir, { recursive: true })
  }

  const locales = config.i18n ? Object.keys(config.i18n.locales) : []
  const versions = config.versions
    ? config.versions.versions.map((v) => v.path)
    : []

  const localeType =
    locales.length > 0 ? locales.map((l) => `'${l}'`).join(' | ') : 'string'
  const versionType =
    versions.length > 0 ? versions.map((v) => `'${v}'`).join(' | ') : 'string'
  const routePathType =
    routePaths && routePaths.length > 0
      ? routePaths.map((p) => `'${p}'`).join(' | ')
      : 'string'

  // Scan for custom mdx-components within the user's docs directory
  const extensions = ['tsx', 'ts', 'jsx', 'js']
  let mdxComponentsImport = ''
  let mdxComponentsTypeRef = ''

  for (const ext of extensions) {
    const fullPath = path.resolve(root, docsDir, `mdx-components.${ext}`)
    if (fs.existsSync(fullPath)) {
      // Compute relative import path from the generated type file to the user component file
      const baseMdxPath = path.join(root, docsDir, 'mdx-components')
      const relativePath = path.relative(dotBoltdocsDir, baseMdxPath)
      const normalizedPath = relativePath.replace(/\\/g, '/')
      const importPath = normalizedPath.startsWith('.')
        ? normalizedPath
        : `./${normalizedPath}`

      mdxComponentsImport = `import type * as MdxComponentsModule from '${importPath}'\n`
      mdxComponentsTypeRef = `      MdxComponents: typeof MdxComponentsModule`
      break
    }
  }

  const routePathAugmentation =
    routePaths && routePaths.length > 0
      ? `\ndeclare global {
  namespace Boltdocs {
    interface RoutePaths {
${routePaths.map((p) => `      '${p}': void`).join('\n')}
    }
  }
}`
      : ''

  const content = `// This file is automatically generated by Boltdocs.
// Do not edit this file manually.

${mdxComponentsImport}declare global {
  namespace Boltdocs {
    interface Types {
      Locale: ${localeType}
      Version: ${versionType}${mdxComponentsTypeRef ? `\n${mdxComponentsTypeRef}` : ''}
    }
  }
}${routePathAugmentation}

export {}
`

  fs.writeFileSync(path.resolve(dotBoltdocsDir, 'types.d.ts'), content)
}

/**
 * Writes a link-tree.json file with all known route paths.
 * Used by the doctor to validate internal links.
 */
export function writeLinkTree(
  routePaths: string[],
  root: string = process.cwd(),
): void {
  const dotBoltdocsDir = path.resolve(root, '.boltdocs', 'generated')
  if (!fs.existsSync(dotBoltdocsDir)) {
    fs.mkdirSync(dotBoltdocsDir, { recursive: true })
  }

  const tree = {
    routes: Array.from(new Set(routePaths)).sort(),
    timestamp: Date.now(),
  }

  fs.writeFileSync(
    path.resolve(dotBoltdocsDir, 'link-tree.json'),
    JSON.stringify(tree, null, 2),
  )
}
